baseURL = 'https://charan.github.io/public'
languageCode = 'en-us'
title = 'Charan Blog'
theme = "hugo-bearblog"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
